dist: xenial
language: cpp
os:
  - linux
arch:
  - ppc64le

services:
  - docker

env:
  jobs:
    - CMD=rocksdbjavastaticdockerppc64le
    - CMD=rocksdbjavastaticdockerppc64lemusl

install:
  - sudo apt-get install -y openjdk-8-jdk || exit $?
  - export PATH=/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)/bin:$PATH
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-$(dpkg --print-architecture)
  - echo "JAVA_HOME=${JAVA_HOME}"
  - which java && java -version
  - which javac && javac -version

script:
  - make jclean clean $CMD

deploy:
  provider: releases
  api_key: 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
  file:
    - $TRAVIS_BUILD_DIR/java/target/librocksdbjni-linux-ppc64le-musl.so
    - $TRAVIS_BUILD_DIR/java/target/librocksdbjni-linux-ppc64le.so
  skip_cleanup: true
  draft: true
  on:
    tags: false