on: [push, pull_request]

jobs:
  armv7_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu_latest ppc
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set ppc
        uses: uraimo/run-on-arch-action@v2
        with:
          arch: ppc64le
          distro: ubuntu_latest

      - name: show ppc
        run: |
          uname -a
          arch

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.13
        with:
          cmake-version: '3.16.x'

      - name: Use cmake
        run: |
          cmake --version
          make --version

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            java/target/frocksdbjni*
